### ISSUE TITLE
iis2tomcat breaks xsendfile

### ISSUE THREAD

**Issue by byrning** [Bilal-S/iis2tomcat#27]
Hi,

Could you please add support for X-Sendfile header processing? 

Right now if one attempts to use https://github.com/stakach/IIS-X-Sendfile-plugin with your connector, an error occurs "Server cannot append header after HTTP headers have been sent", because the IIS-X-Sendfile plugin needs to further process the response from tomcat.

IIS-X-Sendfile checks for the existence of the X-Sendfile header and does the following if it exists:
1. clears the response
2. removes the X-Sendfile header 
3. transmits the file listed in the header back to the browser

I imagine you'd just check for the existence of the header, and if it exists, just pass the data back to IIS instead of flushing to the browser?

**Comment by testciaccount3** [comment]
I am not familiar with the plugin.
The connector does not normally influence the headers that are passed along.
The error you are describing is raised by IIS. It indicates a protocol violation. You are not allowed to send new headers once the transmission has been started. 
Ensure in your coding that you have all the HTTP headers that you will use set before starting the transmission/flushing process. If you have Autoflush detection enabled, disable it or ensure that the values are high enough so that the transmission is not triggered too early.

**Comment by Bilal-S** [comment]
I am not familiar with the plugin.
The connector does not normally influence the headers that are passed along.
The error you are describing is raised by IIS. It indicates a protocol violation. You are not allowed to send new headers once the transmission has been started. 
Ensure in your coding that you have all the HTTP headers that you will use set before starting the transmission/flushing process. If you have Autoflush detection enabled, disable it or ensure that the values are high enough so that the transmission is not triggered too early.

**Comment by byrning** [comment]
Thanks for the response. X-Sendfile essentially hooks onto EndRequest and if a X-Sendfile header exists <cfheader name="X-Sendfile" value="path-fo-private-folder-file">, IIS starts transmitting the file referenced in the header back to the client instead of the response page content. This frees up a lucee (thread and memory) from having to transfer large files with for example <cfcontent file="path-fo-private-folder-file">.

I found out why things are failing. If I comment out line 582 "p_Context.Response.Flush();" in callhandler.cs, everything works.  From what I've read, it is not recommended to call flush and to rather let IIS handle the flushing. Ref: https://www.leansentry.com/HowTo/AspNet-Response-Flush-Poor-Performance

Is that line completely necessary?

**Comment by Bilal-S** [comment]
In short it is needed as this the command that passes data from buffer to client. We can reduce it when the user has not explicitly selected flush options to wait until IIS is ready to clear the buffer. I will check.

**Comment by byrning** [comment]
That should do it, as flush options aren't enabled by default. thanks.

**Comment by Bilal-S** [comment]
reduced system flushing. Please check release [1.0.30](https://github.com/Bilal-S/iis2tomcat/releases/tag/1.0.30)

**Comment by byrning** [comment]
Perfect! Thanks.
