### ISSUE TITLE
executionTimeout attribute in web.config

### ISSUE THREAD

**Issue by davequested** [Bilal-S/iis2tomcat#32]
Hi Bilal

Sorry another strange issue. So we have some long running requests (around an hour). 

We have put in an executionTimeout value:

```
<configuration>
    <system.web>
        <httpRuntime enableVersionHeader="false" maxRequestLength="29296" executionTimeout="3600" />
    </system.web>  
</configuration>

```

But it seems to show the generic executionTimeout error after 360 seconds. 

Is there something else we need to ensure we're doing on the Tomcat / Boncode side? 

In CF we have:

`<cfsetting requesttimeout="3600">`

Our connector in server.xml looks like this:

`<Connector port="8016" protocol="AJP/1.3" redirectPort="8449" tomcatAuthentication="false" maxThreads="1000" connectionTimeout="60000" packetSize="65536"/>`

Our boncode.settings:

```
<Settings>
<Server>localhost</Server>
<Port>8016</Port>
<PacketSize>65536</PacketSize>
<MaxConnections>1000</MaxConnections>
<EnableRemoteAdmin>False</EnableRemoteAdmin>
<EnableHeaderDataSupport>True</EnableHeaderDataSupport>
<EnableAggressiveGC>True</EnableAggressiveGC>
<AllowEmptyHeaders>True</AllowEmptyHeaders>
<EnableAdobeMode>True</EnableAdobeMode>
<EnableHTTPStatusCodes>True</EnableHTTPStatusCodes>
<ResolveRemoteAddrFrom>HTTP_X_FORWARDED_FOR</ResolveRemoteAddrFrom>
<ReadTimeOut>360000</ReadTimeOut>
<LogLevel>0</LogLevel>
</Settings>
```

Thanks in advance

Dave

**Comment by Bilal-S** [comment]
Currently the tomcat connection could terminate after 60s of idle. This could be a timeout issue for you but it would not be 360s. Keeping the HTTP stream open for an hour is not very efficient as it can be used for DOS attacks too easily.

Does your CFML process continue successfully for the hour and you only need to see the results? If so, an alternate approach could be to run two separate processes. One that kicks of the processing and one that views the results from time-to-time. When the process is complete, a summary view is presented.

None of the connection timeouts are in the 360s range:
https://tomcat.apache.org/tomcat-7.0-doc/config/http.html

If your CFML process times out, it would be somewhere in the tomcat container servlet processing timeout. You may need to check the CF boards for timeout management.

**Comment by davequested** [comment]
Very strange, we increased the executionTimeout to 36000 to see if it was a millisecond vs second typo, but it still throw that message at exactly 360 seconds.

We could re-configure some scripts as you suggest, but things like long running upload processes definitely need to hold open the connection and return a 200 OK. 

Must be 360 seconds somewhere?

**Comment by Bilal-S** [comment]
You may also reach the upload limit for IIS for your test case. This is a byte limit rather than time limit and you just happen to reach it at the 360s mark.

https://www.iis.net/configreference/system.webserver/security/requestfiltering/requestlimits


For tomcat in :
../WEB-INF/web.xml

change/add
  <multipart-config>

      <max-file-size>52428800</max-file-size>
      <max-request-size>52428800</max-request-size>
      <file-size-threshold>0<</file-size-threshold>

  </multipart-config>

**Comment by davequested** [comment]
The process actually doesn't receive a lot of data, it just fires a series of requests to CFHTTP and waits till all have been completed. We've run that on lots of different calls, which would very unlikely reach 360 seconds for all the times we've run it. The mystery continues!!!

**Comment by davequested** [comment]
Hi Bilal, is there a way to get BonCode to respect the <cfsettting requesttimeout> setting, much the way that the Adobe connector works? This 360 second issue is becoming quite an issue!

**Comment by Bilal-S** [comment]
Dave,
There is no logical connection between your stated problem case and code in connector. The connector simply does not have a timeout like this. Any connector driven timeout would also register an exception in the Boncode logs. Are you seeing anything there? Thus, it is unlikely to be the source of this timeout. 

Nonetheless, I have tried to replicate your issue using a test case with long running request and have not been able to do so. 

Here is sample code `longrun.cfm`
```
<cfsetting requesttimeout="3600">
<!DOCTYPE HTML>

<html>
<head>
    <title>Long Running Task</title>
</head>

<body>
    <cfoutput>
        Start: 
        #Now()#<BR>
    

        <cfscript>
            flush; 
            sleep(600 * 1000);	
        </cfscript>

        End:
        #Now()#<BR>
     </cfoutput> 
</body>
    
</html>
```

Corresponding change in `web.config`:
```
<configuration>
    <location path="longrun.cfm">
    	<system.web>
        	<httpRuntime executionTimeout="3600"/>
    	</system.web>
    </location>
   ...
```


Thus, given the data a more likely source is misconfiguration in IIS or routing infrastructure.
Simple test for yourself:
a) Run all tests on server not via routers or network
b) Lower the timeout to three seconds in web.config. Run your page. Does it timeout? If not you are not making changes to correct configuration area
c) Increase the timeout in web.config, run test locally? Still getting the exception? Check other software, replace connector with alternate connection mechanism and try again.  If c) does not timeout, then, you have a router, web-app firewall or something similar timeout: check out your infrastructure for timeout values.

Overall I need a minimal test case that runs on server and produces the exception, otherwise, I will not be able to replicate and/or fix.

Hope this helps,
Bilal

**Comment by Bilal-S** [comment]
Any updates? If not, I will close it for now and we can open a related case later.

**Comment by davequested** [comment]
Hi Bilal

My apologies for not getting back sooner.

We found the issue. It was the ReadTimeOut, it was missing an extra 0!

Dave
