### ISSUE TITLE
IIS Worker Process High CPU HELP

### ISSUE THREAD

**Issue by msp1kpj** [Bilal-S/iis2tomcat#35]
We are having high CPU issues on our IIS server when the connection to the tomcat server gets interrupted by the load balancer.  I was able to analys the Windows Demp file but I am not sure what I am looking for. We are running on a linux server and load balancing between several instances.

I need Help and I don't know what to look at next. We thought it was IIS rewrites but we have removed all and still have the issues.

Here are the results:

In w3wp (7).DMP GC is running in this process. The Thread that triggered the GC is 23

Thread 23 - System ID 11340
Entry point   ntdll!RtlUserThreadStart+34 
Create time   12/6/2016 10:26:01 AM 
Time spent in user mode   0 Days 00:02:58.390 
Time spent in kernel mode   0 Days 00:04:50.609 

This thread is not fully resolved and may or may not be a problem. Further analysis of these threads may be required.

.NET Call Stack

Function 
System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr, System.Web.RequestNotificationStatus ByRef) 
System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr, System.Web.RequestNotificationStatus ByRef) 
System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr, System.Web.RequestNotificationStatus ByRef) 
System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr, System.Web.RequestNotificationStatus ByRef) 

Full Call Stack

Function   Source 
ntdll!NtWaitForSingleObject+a    
KERNELBASE!WaitForSingleObjectEx+94    
clr!CLREventWaitHelper2+38    
clr!CLREventWaitHelper+1f    
clr!CLREventBase::WaitEx+70    
clr!SVR::gc_heap::wait_for_gc_done+57    
clr!SVR::GCHeap::GarbageCollectGeneration+1da    
clr!SVR::GCHeap::Alloc+21c    
clr!Alloc+60    
clr!JIT_NewArr1+4cf    
0x00007ff9`ebe6b286    
0x00007ff9`ebe6a6f5    
0x00007ff9`ebe6a276    
0x00007ff9`ebe6140f    
System_Web_ni+2f6271    
System_Web_ni+2bd495    
System_Web_ni+2dabaa    
System_Web_ni+2bd6a3    
System_Web_ni+2b75de    
System_Web_ni+2c0561    
System_Web_ni+2bff92    
System_Web_ni+a15ea1    
clr!UMThunkStub+6e    
webengine4!W3_MGD_HANDLER::ProcessNotification+78    
webengine4!W3_MGD_HANDLER::DoWork+34f    
webengine4!RequestDoWork+34e    
webengine4!CMgdEngHttpModule::OnExecuteRequestHandler+21    
iiscore!NOTIFICATION_CONTEXT::RequestDoWork+224    
iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+198    
iiscore!NOTIFICATION_CONTEXT::CallModules+36    
iiscore!NOTIFICATION_MAIN::DoWork+4b4    
iiscore!W3_CONTEXT_BASE::IndicateCompletion+97    
webengine4!MgdIndicateCompletion+60    
System_Web_ni+3696cb    
System_Web_ni+2c074f    
System_Web_ni+2bff92    
System_Web_ni+a15ea1    
clr!UMThunkStub+6e    
webengine4!W3_MGD_HANDLER::ProcessNotification+78    
webengine4!W3_MGD_HANDLER::DoWork+34f    
webengine4!RequestDoWork+34e    
webengine4!CMgdEngHttpModule::OnAuthenticateRequest+1f    
iiscore!NOTIFICATION_CONTEXT::RequestDoWork+ea    
iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+198    
iiscore!NOTIFICATION_CONTEXT::CallModules+36    
iiscore!NOTIFICATION_MAIN::DoWork+422    
iiscore!W3_CONTEXT_BASE::StartNotificationLoop+94    
iiscore!W3_CONTEXT::ExecuteRequest+297    
defdoc!W3_DEFAULT_DOC_HANDLER::DoWork+73d    
defdoc!RequestDoWork+20d    
defdoc!CIISHttpModule::OnExecuteRequestHandler+1a    
iiscore!NOTIFICATION_CONTEXT::RequestDoWork+224    
iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+198    
iiscore!NOTIFICATION_CONTEXT::CallModules+36    
iiscore!NOTIFICATION_MAIN::DoWork+4b4    
iiscore!W3_CONTEXT_BASE::StartNotificationLoop+94    
iiscore!W3_CONTEXT::ExecuteRequest+297    
webengine4!W3_MGD_HANDLER::DoChildExecute+7c    
webengine4!W3_MGD_HANDLER::ProcessNotification+9c    
webengine4!W3_MGD_HANDLER::DoWork+34f    
webengine4!RequestDoWork+34e    
webengine4!CMgdEngHttpModule::OnExecuteRequestHandler+21    
iiscore!NOTIFICATION_CONTEXT::RequestDoWork+224    
iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+198    
iiscore!NOTIFICATION_CONTEXT::CallModules+36    
iiscore!NOTIFICATION_MAIN::DoWork+4b4    
iiscore!W3_CONTEXT_BASE::IndicateCompletion+97    
webengine4!MgdIndicateCompletion+60    
System_Web_ni+3696cb    
System_Web_ni+2c074f    
System_Web_ni+2bff92    
System_Web_ni+a15ea1    
clr!UM2MThunk_WrapperHelper+43    
clr!UM2MThunk_Wrapper+5a    
clr!Thread::DoADCallBack+13c    
clr!UM2MDoADCallBack+91    
clr!UMThunkStub+26d    
webengine4!W3_MGD_HANDLER::ProcessNotification+78    
webengine4!ProcessNotificationCallback+42    
clr!UnManagedPerAppDomainTPCount::DispatchWorkItem+134    
clr!ThreadpoolMgr::ExecuteWorkRequest+64    
clr!ThreadpoolMgr::WorkerThreadStart+2b6    
clr!Thread::intermediateThreadProc+7d    
kernel32!BaseThreadInitThunk+22    
ntdll!RtlUserThreadStart+34

**Comment by Bilal-S** [comment]
this looks on the surface like a garbage collection process is hanging.
do you set a timeout in IIS for the threads? If so what is it?
Also what version of the connector are you using?

**Comment by msp1kpj** [comment]
We are on 1.0.32. We do not have any overrides set in the web.config so I am guessing we are using the default timeout if there is any.

**Comment by Bilal-S** [comment]
Can you reduce your idle timeout on the process. Like in this image:
![idletimeout](https://cloud.githubusercontent.com/assets/668901/21076099/ed1c1968-bef0-11e6-8285-84418ea0bada.PNG)

Also do you have a timeout on the tomcat side for your connection? Can you share the AJP protocol definition line from your tomcat server.xml file. Similarly can you share your connector configuration file. You can find the active connector configuration file by running a connector directive locally on the server. Such as:
`http://localhost/a.jsp?BonCodeConnectorVersion=true`

You should remove any sensitive data from the outputs before sharing.

**Comment by msp1kpj** [comment]
Hers is the IIS Application Setting...
![image](https://cloud.githubusercontent.com/assets/7109246/21087103/6e6792ac-bfe8-11e6-8837-46d6a9428c27.png)


Here is the XML 
```
<?xml version="1.0" encoding="UTF-8"?><Settings>
    <Server>10.10.30.15</Server>
    <Port>50204</Port>
	<EnableRemoteAdmin>False</EnableRemoteAdmin>
	<EnableHeaderDataSupport>True</EnableHeaderDataSupport>
	<ForceSecureSession>False</ForceSecureSession>
	<AllowEmptyHeaders>False</AllowEmptyHeaders>
	<ForceSecureSession>False</ForceSecureSession>
	<DocRoot>/mnt/sites/************/wwwroot</DocRoot>
	<TomcatConnectErrorURL>/probes/TomcatErrorMessage.aspx</TomcatConnectErrorURL>
    <SupportEmail>techsupport-audiencerewards@vansontech.com</SupportEmail>
    <SiteName>audiencerewards-public.vts0.com</SiteName>
    <LogLevel>0</LogLevel>
    <LogDir>c:\temp</LogDir>
</Settings>

```
Tomcat Config 

```
<!DOCTYPE server-xml [
  <!ENTITY vhosts-config SYSTEM "file:///mnt/config/Tomcat/cluster_default/tomcat/conf/vhosts.xml" >
  <!ENTITY cluster-config SYSTEM "file:///mnt/config/Tomcat/cluster_default/tomcat/conf/cluster.xml" >
]>
<Server port="8800" shutdown="SHUTDOWN">
  <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
  <Listener className="org.apache.catalina.core.JasperListener" />
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
  <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />
  <Service name="Catalina">
    <Connector port="8801" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443"
                maxHttpHeaderSize="8192" maxThreads="150" minSpareThreads="25"
                enableLookups="false" acceptCount="100" disableUploadTimeout="true" />
    <Connector port="8802" URIEncoding="UTF-8" protocol="AJP/1.3" redirectPort="8443"/>
    <Engine name="Catalina" defaultHost="default">
      <Valve className="org.apache.catalina.valves.RemoteIpValve" protocolHeader="server-port" protocolHeaderHttpsValue="81"  />
      <Valve className="org.apache.catalina.valves.CrawlerSessionManagerValve" crawlerUserAgents=".*ServerNanny.*|.*CFSCHEDULE.*|.*[bB]ot.*|.*Yahoo! Slurp.*|.*Feedfetcher-Google.*" sessionInactiveInterval="60" />
        &cluster-config;
        &vhosts-config;
    </Engine>
  </Service>
</Server>

```

**Comment by Bilal-S** [comment]
Ken,
Here are a few things I am noticing:
### Connector (BonCodeAJP13.settings) file
a) There additional keys (SupportEmail, SiteName) stored in connector file that are not used directly by connector. They will be ignored but if the intent is for them to be used you need to be aware.
b) There is no MaxConnection attribute. You should consider this for sites working on under load `<MaxConnections>500</MaxConnections>`. This should reduce the reconnect attempts and establish a proper connection pool.
c) Your AJP port assignment `8802` does not match your configuration for your Tomcat server.xml (`50204`). This maybe because you are going through some sort of load balancer which, in turn, does map it?
d) Consider increasing packet size directive (this needs to occur for *both* tomcat and boncode:
`<PacketSize>65536</PacketSize>` 

### Tomcat server.xml
a) Your AJP port setup seems mismatched see above point c)
b) Your protocol setup is very basic and seems missing tuning for load suggestion is to consider changes:
`<Connector port="8802" URIEncoding="UTF-8" protocol="AJP/1.3" redirectPort="8443"/>`
to
`<Connector port="8802" URIEncoding="UTF-8" protocol="AJP/1.3" redirectPort="8443" maxThreads="1000" connectionTimeout="60000" packetSize="65536" />`

### General
- Since the error trace indicated GC (Garbage Collect issues). Also consider lowering your Idle-Timeout minutes down between 2-5.
-  Consider switching to "Workstation GC" which behaves differently. To do so do this:
 in the .net configuration file. For 64-bit .net 4 this file is located typically in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Aspnet.config add the line 
`<gcServer enabled="false"/>` under `<runtime>` node

**Comment by Bilal-S** [comment]
Ken,
You might also want to give version 1.0.33 a try. This may not be related but I would like to exclude the issue here as other users were reporting a link.
Best,
Bilal

**Comment by msp1kpj** [comment]
Bilal,

We are trying these changes on our QA environment first.

The port difference between the configuration file is because we are going through a load balancer.

**Comment by Bilal-S** [comment]
Sure thing.
Please make sure when using timeouts that they are in sync, E.g. if you have a two minute idle connection timeout on tomcat you need to have  a two minute idle timeout on IIS (preferebly slightly shorter).  Otherwise, you will have "Generic errors" recorded in your log because the channel was shut down on one side only.

**Comment by msp1kpj** [comment]
Bilal,

Setting changes to our QA environment are running great. I have a few more question.

Since we are running behind though a load balancer to connect 1 IIS servers to many Tomcat servers how should I setup the connection pools? 

I have 500 connection in  IIS per site and 500 connection on the AJP setting .
What do I do when there are multiple site?

**Comment by Bilal-S** [comment]
Ken,
If you running a load balancer for the port you can increase the IIS connection setting accordingly. For example if you have three tomcat machines that can handle about 500 connections each, you would increase the IIS setting to 1500 (the aggregate). This is with the following assumption:
a)  your IIS machine is able to handle the load which is normally the case. Otherwise you would also spread the load to your web-layer via another load-balancer.
b) your load balancer is smart enough to make sure that the connection are truly balanced and does not overload a singular site.

HTH,
Bilal

**Comment by Bilal-S** [comment]
closing issue for now. can be opened again later if needed.
