### ISSUE TITLE
What are correct setting for chunk encoding?

### ISSUE THREAD

**Issue by AndreyGritsik** [Bilal-S/iis2tomcat#44]
Hi Bilal.

I got NET:: ERR_INVALID_CHUNKED_ENCODING error. Maybe something wrong with my settings?

Description of configuration:

I've configured Boncode AJP 1/3 connector ver. 1.033 using Windows 10 IIS and found in Windows log error from Boncode AJP 1/3 connector:

BonCodeAJP13.settings file's content:

```
<Settings>
<Server>localhost</Server>
<Port>8009</Port>
<EnableHeaderDataSupport>True</EnableHeaderDataSupport>
<ForceSecureSession>False</ForceSecureSession>
<FlushThresholdBytes>5242880</FlushThresholdBytes>
<PacketSize>65536</PacketSize>
</Settings>
```

Tomcat's server.xml AJP1/3 connector's row:

`<Connector port="8009" protocol="AJP/1.3" redirectPort="16080" tomcatAuthentication="false" maxThreads="1000" connectionTimeout="121000" packetSize="65536"/>`

When Tomcat sends response  with the content bellow:

```
HTTP/1.1 200 OK
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: application/octet-stream
Server: Microsoft-IIS/10.0
Content-Disposition: attachment; filename="file.ZIP"
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 09 Feb 2017 16:36:51 GMT

```
I've got NET:: ERR_INVALID_CHUNKED_ENCODING error on Chrome browser.

Thanks in advance.

**Comment by Bilal-S** [comment]
What happens when you take out <FlushThresholdBytes>?

**Comment by AndreyGritsik** [comment]
Without <FlushThresholdBytes> tag is the same result: NET:: ERR_INVALID_CHUNKED_ENCODING ...

**Comment by Bilal-S** [comment]
OK. Thanks for checking.

You would need to analyze your full package list and HTTP headers.
You can avoid chunking by simply setting the content-length of your transmission, e.g.  the size of the file you are transferring. IIS will switch automatically into chunked mode transfer to client if you do not provide Content-Length HTTP header.
If you used chunked transfers it requires that your response correctly generates chunk terminations etc.
Is that happening?

If you cannot add the content-length and believe this to be a bug in the connector I will need a minimum viable test case so that I can recreate.

Best,
Bilal

**Comment by Bilal-S** [comment]
closing for now. Will reopen if test case.
