### ISSUE TITLE
Add support for websockets

### ISSUE THREAD

**Issue by redtopia** [Bilal-S/iis2tomcat#51]
A new websocket extension was recently released for Lucee 5.1, but does not appear to work with IIS/Boncode because the Boncode adapter does not pass websocket requests through to Tomcat. If this can be achieved, please let me know how to configure it, otherwise, consider this a feature request.

The Lucee websocket extension is here:

https://github.com/isapir/lucee-websocket

**Comment by Bilal-S** [comment]
Boncode is a translator between AJP and HTTP protocols. Websocket protocol is a protocol on its own WS (RFC 6455). 
The potential is to create a bridge between AJP and WS protocol but the implementation would be proprietary since we have to invent it most likely mimicking the common lifecycle events:

onHandshake
onOpen
onMessage
onError
onClose
onChannelOpen
onChannelClose
onSubscribe
onUnsubscribe

This would most likely not work like igal's extensions

**Comment by redtopia** [comment]
I don't know the nuts and bolts of how it's all put together, but I believe Igal's extension uses the tomcat websocket class. It's not possible to simply pass all websocket activity to Tomcat?

https://tomcat.apache.org/tomcat-8.5-doc/web-socket-howto.html#Overview

**Comment by Bilal-S** [comment]
You can try to use ARR3 as people discuss here:
http://stackoverflow.com/questions/33272786/websockets-on-tomcat-8-iis-8-with-arr-3-are-not-working

**Comment by redtopia** [comment]
Meaning use ARR to route websocket traffic directly to tomcat?

**Comment by Bilal-S** [comment]
I am interpreting it as such. I have not done this.
