### ISSUE TITLE
How to get IIS site name, form connector to Tomcat servlet

### ISSUE THREAD

**Issue by mayuranchalia** [Bilal-S/iis2tomcat#52]

**Comment by Bilal-S** [comment]
This is not part of connector features.
You will need to do it yourself.

You can get the unique INSTANCE_ID for your site by enabling header data support (see EnableHeaderDataSupport setting in manual). 
Then you will have a new HTTP variable: `x-webserver-context`
which will have a prefix of `W3SVC` followed by INSTANCE_ID. For example W3SVC23, means instance_id = 23.

Otherwise, you will need to figure out how to make a call to IIS and retrieve the sitename property:
https://msdn.microsoft.com/en-us/library/system.web.hosting.hostingenvironment.sitename(v=vs.110).aspx

It will not be possible to add this to the connector at this time.

**Comment by mayuranchalia** [comment]
Thanks a lot for quick response.

Regards
Mayur Jain
