### ISSUE TITLE
HTTP 404

### ISSUE THREAD

**Issue by Subramanian-Palanisami** [Bilal-S/iis2tomcat#72]
Hi Bilal,

1. added virtual directory under my website (www.xyz.in) called **/eacc**.
2. physical path: C:\Tomcat\apache-tomcat-9.0.7\webapps\eacc
           Note:  folders available under above physical path:
           1. META-INF & 2. WEB-INF
3. Clieck on "Handler Mappings" of **eacc** vd folder.
4. click on Add Managed Handler:
5. Request Path: *
6. Type: BonCodeIIS.BonCodeCallHandler
7. Name: BonCode-WL-Handler
8. Click on "Ok" button. 
9. Restart IIS.

While trigger url http://www.xyx.in/eacc/api/fetchVendors in postman, getting following exception:

> Server Error in '/' Application.
> The resource cannot be found.
> Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

> Requested URL: /eacc/api/fetchVendors

if i do localhost:8080/eacc/api/fetchVendors  in postman, Have get results.

```
<Settings>
  <Port>8009</Port>
  <Server>localhost</Server>   
  <MaxConnections>0</MaxConnections>
  <LogLevel>2</LogLevel>  
  <LogDir>C:\ealogs</LogDir>  
  <FlushThreshold>0</FlushThreshold>
  <EnableRemoteAdmin>False</EnableRemoteAdmin>

</Settings>

```
Connector version: 1.0.28
I have set  LogLevel as 1 or 2 with LogDir. Have not seen any log file generated.
uninstall and install with "All Sites" options. But still same issue.

I have created sample "Hello World!!" index.html file under C:\Tomcat\apache-tomcat-9.0.7\webapps\eacc.  and hitting http://www.xyx.in/eacc/  shows "Hello World!!" in browser. This is working only with out wildcard handler mapping. even this not working with wildcard mappings.

Not sure what i missed here, could you please help me to resolve this issue.

Regards,
Subramanian Palanisami

**Comment by Bilal-S** [comment]
closed

**Comment by Bilal-S** [comment]
Subramanian :
First I would recommend that you upgrade to latest version which is 1.0.39.
If you do not see an error or log entry in BonCode log files, the connector
is not triggered, meaning the issue is with an element prior to the
connector.

The most likely cause of 404 from IIS is that you require a corresponding
path or directory. Remove that requirement for wildcard mapping as this
would be processed by tomcat. Change your mapping like in the attached
image.

If the 404 is from Tomcat you need to explore the tomcat error log and fix
the issue there.

Best,
Bilal
